//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace bob.CaeceWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wbsTransSoap", Namespace="wbsTransNS")]
    public partial class wbsTrans : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getDatosAspirantesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getContactoCaeceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEstadoDniOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHistoriaAcademicaXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHistoriaAcademicaJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPlanEstudioXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPlanEstudioJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCursosAbiertosXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCursosAbiertosJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMesasAbiertasXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMesasAbiertasJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback autenticacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wbsTrans() {
            this.Url = global::bob.Properties.Settings.Default.bob_CaeceWS_wbsTrans;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getDatosAspirantesCompletedEventHandler getDatosAspirantesCompleted;
        
        /// <remarks/>
        public event getContactoCaeceCompletedEventHandler getContactoCaeceCompleted;
        
        /// <remarks/>
        public event getEstadoDniCompletedEventHandler getEstadoDniCompleted;
        
        /// <remarks/>
        public event getHistoriaAcademicaXMLCompletedEventHandler getHistoriaAcademicaXMLCompleted;
        
        /// <remarks/>
        public event getHistoriaAcademicaJSONCompletedEventHandler getHistoriaAcademicaJSONCompleted;
        
        /// <remarks/>
        public event getPlanEstudioXMLCompletedEventHandler getPlanEstudioXMLCompleted;
        
        /// <remarks/>
        public event getPlanEstudioJSONCompletedEventHandler getPlanEstudioJSONCompleted;
        
        /// <remarks/>
        public event getCursosAbiertosXMLCompletedEventHandler getCursosAbiertosXMLCompleted;
        
        /// <remarks/>
        public event getCursosAbiertosJSONCompletedEventHandler getCursosAbiertosJSONCompleted;
        
        /// <remarks/>
        public event getMesasAbiertasXMLCompletedEventHandler getMesasAbiertasXMLCompleted;
        
        /// <remarks/>
        public event getMesasAbiertasJSONCompletedEventHandler getMesasAbiertasJSONCompleted;
        
        /// <remarks/>
        public event autenticacionCompletedEventHandler autenticacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getDatosAspirantes", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getDatosAspirantes(string token, string fecha) {
            object[] results = this.Invoke("getDatosAspirantes", new object[] {
                        token,
                        fecha});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getDatosAspirantesAsync(string token, string fecha) {
            this.getDatosAspirantesAsync(token, fecha, null);
        }
        
        /// <remarks/>
        public void getDatosAspirantesAsync(string token, string fecha, object userState) {
            if ((this.getDatosAspirantesOperationCompleted == null)) {
                this.getDatosAspirantesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDatosAspirantesOperationCompleted);
            }
            this.InvokeAsync("getDatosAspirantes", new object[] {
                        token,
                        fecha}, this.getDatosAspirantesOperationCompleted, userState);
        }
        
        private void OngetDatosAspirantesOperationCompleted(object arg) {
            if ((this.getDatosAspirantesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDatosAspirantesCompleted(this, new getDatosAspirantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getContactoCaece", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getContactoCaece(string token, string fecha) {
            object[] results = this.Invoke("getContactoCaece", new object[] {
                        token,
                        fecha});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getContactoCaeceAsync(string token, string fecha) {
            this.getContactoCaeceAsync(token, fecha, null);
        }
        
        /// <remarks/>
        public void getContactoCaeceAsync(string token, string fecha, object userState) {
            if ((this.getContactoCaeceOperationCompleted == null)) {
                this.getContactoCaeceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetContactoCaeceOperationCompleted);
            }
            this.InvokeAsync("getContactoCaece", new object[] {
                        token,
                        fecha}, this.getContactoCaeceOperationCompleted, userState);
        }
        
        private void OngetContactoCaeceOperationCompleted(object arg) {
            if ((this.getContactoCaeceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getContactoCaeceCompleted(this, new getContactoCaeceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getEstadoDni", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getEstadoDni(string token, string dni) {
            object[] results = this.Invoke("getEstadoDni", new object[] {
                        token,
                        dni});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getEstadoDniAsync(string token, string dni) {
            this.getEstadoDniAsync(token, dni, null);
        }
        
        /// <remarks/>
        public void getEstadoDniAsync(string token, string dni, object userState) {
            if ((this.getEstadoDniOperationCompleted == null)) {
                this.getEstadoDniOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEstadoDniOperationCompleted);
            }
            this.InvokeAsync("getEstadoDni", new object[] {
                        token,
                        dni}, this.getEstadoDniOperationCompleted, userState);
        }
        
        private void OngetEstadoDniOperationCompleted(object arg) {
            if ((this.getEstadoDniCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEstadoDniCompleted(this, new getEstadoDniCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getHistoriaAcademicaXML", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getHistoriaAcademicaXML(string token, string matricula) {
            object[] results = this.Invoke("getHistoriaAcademicaXML", new object[] {
                        token,
                        matricula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getHistoriaAcademicaXMLAsync(string token, string matricula) {
            this.getHistoriaAcademicaXMLAsync(token, matricula, null);
        }
        
        /// <remarks/>
        public void getHistoriaAcademicaXMLAsync(string token, string matricula, object userState) {
            if ((this.getHistoriaAcademicaXMLOperationCompleted == null)) {
                this.getHistoriaAcademicaXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHistoriaAcademicaXMLOperationCompleted);
            }
            this.InvokeAsync("getHistoriaAcademicaXML", new object[] {
                        token,
                        matricula}, this.getHistoriaAcademicaXMLOperationCompleted, userState);
        }
        
        private void OngetHistoriaAcademicaXMLOperationCompleted(object arg) {
            if ((this.getHistoriaAcademicaXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHistoriaAcademicaXMLCompleted(this, new getHistoriaAcademicaXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getHistoriaAcademicaJSON", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getHistoriaAcademicaJSON(string token, string matricula) {
            object[] results = this.Invoke("getHistoriaAcademicaJSON", new object[] {
                        token,
                        matricula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getHistoriaAcademicaJSONAsync(string token, string matricula) {
            this.getHistoriaAcademicaJSONAsync(token, matricula, null);
        }
        
        /// <remarks/>
        public void getHistoriaAcademicaJSONAsync(string token, string matricula, object userState) {
            if ((this.getHistoriaAcademicaJSONOperationCompleted == null)) {
                this.getHistoriaAcademicaJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHistoriaAcademicaJSONOperationCompleted);
            }
            this.InvokeAsync("getHistoriaAcademicaJSON", new object[] {
                        token,
                        matricula}, this.getHistoriaAcademicaJSONOperationCompleted, userState);
        }
        
        private void OngetHistoriaAcademicaJSONOperationCompleted(object arg) {
            if ((this.getHistoriaAcademicaJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHistoriaAcademicaJSONCompleted(this, new getHistoriaAcademicaJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getPlanEstudioXML", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getPlanEstudioXML(string token, string matricula) {
            object[] results = this.Invoke("getPlanEstudioXML", new object[] {
                        token,
                        matricula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getPlanEstudioXMLAsync(string token, string matricula) {
            this.getPlanEstudioXMLAsync(token, matricula, null);
        }
        
        /// <remarks/>
        public void getPlanEstudioXMLAsync(string token, string matricula, object userState) {
            if ((this.getPlanEstudioXMLOperationCompleted == null)) {
                this.getPlanEstudioXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPlanEstudioXMLOperationCompleted);
            }
            this.InvokeAsync("getPlanEstudioXML", new object[] {
                        token,
                        matricula}, this.getPlanEstudioXMLOperationCompleted, userState);
        }
        
        private void OngetPlanEstudioXMLOperationCompleted(object arg) {
            if ((this.getPlanEstudioXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPlanEstudioXMLCompleted(this, new getPlanEstudioXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getPlanEstudioJSON", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPlanEstudioJSON(string token, string matricula) {
            object[] results = this.Invoke("getPlanEstudioJSON", new object[] {
                        token,
                        matricula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPlanEstudioJSONAsync(string token, string matricula) {
            this.getPlanEstudioJSONAsync(token, matricula, null);
        }
        
        /// <remarks/>
        public void getPlanEstudioJSONAsync(string token, string matricula, object userState) {
            if ((this.getPlanEstudioJSONOperationCompleted == null)) {
                this.getPlanEstudioJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPlanEstudioJSONOperationCompleted);
            }
            this.InvokeAsync("getPlanEstudioJSON", new object[] {
                        token,
                        matricula}, this.getPlanEstudioJSONOperationCompleted, userState);
        }
        
        private void OngetPlanEstudioJSONOperationCompleted(object arg) {
            if ((this.getPlanEstudioJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPlanEstudioJSONCompleted(this, new getPlanEstudioJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getCursosAbiertosXML", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCursosAbiertosXML(string token) {
            object[] results = this.Invoke("getCursosAbiertosXML", new object[] {
                        token});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCursosAbiertosXMLAsync(string token) {
            this.getCursosAbiertosXMLAsync(token, null);
        }
        
        /// <remarks/>
        public void getCursosAbiertosXMLAsync(string token, object userState) {
            if ((this.getCursosAbiertosXMLOperationCompleted == null)) {
                this.getCursosAbiertosXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCursosAbiertosXMLOperationCompleted);
            }
            this.InvokeAsync("getCursosAbiertosXML", new object[] {
                        token}, this.getCursosAbiertosXMLOperationCompleted, userState);
        }
        
        private void OngetCursosAbiertosXMLOperationCompleted(object arg) {
            if ((this.getCursosAbiertosXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCursosAbiertosXMLCompleted(this, new getCursosAbiertosXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getCursosAbiertosJSON", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCursosAbiertosJSON(string token) {
            object[] results = this.Invoke("getCursosAbiertosJSON", new object[] {
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCursosAbiertosJSONAsync(string token) {
            this.getCursosAbiertosJSONAsync(token, null);
        }
        
        /// <remarks/>
        public void getCursosAbiertosJSONAsync(string token, object userState) {
            if ((this.getCursosAbiertosJSONOperationCompleted == null)) {
                this.getCursosAbiertosJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCursosAbiertosJSONOperationCompleted);
            }
            this.InvokeAsync("getCursosAbiertosJSON", new object[] {
                        token}, this.getCursosAbiertosJSONOperationCompleted, userState);
        }
        
        private void OngetCursosAbiertosJSONOperationCompleted(object arg) {
            if ((this.getCursosAbiertosJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCursosAbiertosJSONCompleted(this, new getCursosAbiertosJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getMesasAbiertasXML", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getMesasAbiertasXML(string token, string examen_id) {
            object[] results = this.Invoke("getMesasAbiertasXML", new object[] {
                        token,
                        examen_id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getMesasAbiertasXMLAsync(string token, string examen_id) {
            this.getMesasAbiertasXMLAsync(token, examen_id, null);
        }
        
        /// <remarks/>
        public void getMesasAbiertasXMLAsync(string token, string examen_id, object userState) {
            if ((this.getMesasAbiertasXMLOperationCompleted == null)) {
                this.getMesasAbiertasXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMesasAbiertasXMLOperationCompleted);
            }
            this.InvokeAsync("getMesasAbiertasXML", new object[] {
                        token,
                        examen_id}, this.getMesasAbiertasXMLOperationCompleted, userState);
        }
        
        private void OngetMesasAbiertasXMLOperationCompleted(object arg) {
            if ((this.getMesasAbiertasXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMesasAbiertasXMLCompleted(this, new getMesasAbiertasXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/getMesasAbiertasJSON", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getMesasAbiertasJSON(string token, string examen_id) {
            object[] results = this.Invoke("getMesasAbiertasJSON", new object[] {
                        token,
                        examen_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMesasAbiertasJSONAsync(string token, string examen_id) {
            this.getMesasAbiertasJSONAsync(token, examen_id, null);
        }
        
        /// <remarks/>
        public void getMesasAbiertasJSONAsync(string token, string examen_id, object userState) {
            if ((this.getMesasAbiertasJSONOperationCompleted == null)) {
                this.getMesasAbiertasJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMesasAbiertasJSONOperationCompleted);
            }
            this.InvokeAsync("getMesasAbiertasJSON", new object[] {
                        token,
                        examen_id}, this.getMesasAbiertasJSONOperationCompleted, userState);
        }
        
        private void OngetMesasAbiertasJSONOperationCompleted(object arg) {
            if ((this.getMesasAbiertasJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMesasAbiertasJSONCompleted(this, new getMesasAbiertasJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("wbsTransNS/autenticacion", RequestNamespace="wbsTransNS", ResponseNamespace="wbsTransNS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string autenticacion(string token, string alumno_id, string password) {
            object[] results = this.Invoke("autenticacion", new object[] {
                        token,
                        alumno_id,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void autenticacionAsync(string token, string alumno_id, string password) {
            this.autenticacionAsync(token, alumno_id, password, null);
        }
        
        /// <remarks/>
        public void autenticacionAsync(string token, string alumno_id, string password, object userState) {
            if ((this.autenticacionOperationCompleted == null)) {
                this.autenticacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnautenticacionOperationCompleted);
            }
            this.InvokeAsync("autenticacion", new object[] {
                        token,
                        alumno_id,
                        password}, this.autenticacionOperationCompleted, userState);
        }
        
        private void OnautenticacionOperationCompleted(object arg) {
            if ((this.autenticacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.autenticacionCompleted(this, new autenticacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getDatosAspirantesCompletedEventHandler(object sender, getDatosAspirantesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDatosAspirantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDatosAspirantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getContactoCaeceCompletedEventHandler(object sender, getContactoCaeceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getContactoCaeceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getContactoCaeceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getEstadoDniCompletedEventHandler(object sender, getEstadoDniCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEstadoDniCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEstadoDniCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getHistoriaAcademicaXMLCompletedEventHandler(object sender, getHistoriaAcademicaXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHistoriaAcademicaXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHistoriaAcademicaXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getHistoriaAcademicaJSONCompletedEventHandler(object sender, getHistoriaAcademicaJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHistoriaAcademicaJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHistoriaAcademicaJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getPlanEstudioXMLCompletedEventHandler(object sender, getPlanEstudioXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPlanEstudioXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPlanEstudioXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getPlanEstudioJSONCompletedEventHandler(object sender, getPlanEstudioJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPlanEstudioJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPlanEstudioJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getCursosAbiertosXMLCompletedEventHandler(object sender, getCursosAbiertosXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCursosAbiertosXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCursosAbiertosXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getCursosAbiertosJSONCompletedEventHandler(object sender, getCursosAbiertosJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCursosAbiertosJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCursosAbiertosJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getMesasAbiertasXMLCompletedEventHandler(object sender, getMesasAbiertasXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMesasAbiertasXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMesasAbiertasXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getMesasAbiertasJSONCompletedEventHandler(object sender, getMesasAbiertasJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMesasAbiertasJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMesasAbiertasJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void autenticacionCompletedEventHandler(object sender, autenticacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class autenticacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal autenticacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591